name: Main test
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: dependencies
      run: |
        python3.12 -m pip install flake8
    - name: Flake8
      run: python3.12 -m flake8 clinic/
  tests:
    name: tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Установка зависимостей
      run: pip install -r requirements.txt
    - name: Настройка базы данных
      run: |
        sudo apt-get install postgresql-client
        psql -h localhost -U user -d test_db -c "CREATE DATABASE test_db;"
      env:
        PGPASSWORD: password
    - name: Запуск тестов
      run: python manage.py test tests/
      env:
        DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DBNAME}
