name: Main test
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: dependencies
      run: |
        python3.12 -m pip install flake8
    - name: Flake8
      run: python3.12 -m flake8 clinic/
  tests:
    name: tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Установка зависимостей
      run: pip install -r requirements.txt
    - name: Проверка состояния контейнера PostgreSQL
      run: docker ps -a
    - name: Настройка базы данных
      run: |
        sudo apt-get install postgresql-client
        psql -h localhost -U ${{ secrets.PG_USER }} -d ${{ secrets.PG_DBNAME }} -c "CREATE DATABASE ${{ secrets.PG_DBNAME }};"
      env:
        PGPASSWORD: ${{ secrets.PG_PASSWORD }}
    - name: Запуск тестов
      run: python manage.py test tests/
      env:
        DATABASE_URL: postgres://${{ secrets.PG_USER }}:${{ secrets.PG_PASSWORD }}@${{ secrets.PG_HOST }}:${{ secrets.PG_PORT }}/${{ secrets.PG_DBNAME }}
